import Head from 'next/head'
import React from 'react'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import Header from './Header'
import Start from './Start'
import About from './About'
import Projects from './Projects'
import Skills from './Skiils'
import Footer from './Footer'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <React.Fragment>
      <Head>
        <title>DevJhones Developer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/r.png" />
      </Head>

      <Header/>

      <Start/>

      <About/>

      <Projects/>

      <Skills/>

      <Footer/>
    </React.Fragment>
  )
}
